spring:
  profiles:
    active:
      - avro

---

spring:
  config:
    activate:
      on-profile: string
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: deal-avro-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        schema.registry.url: http://localhost:8081

---

spring:
  config:
    activate:
      on-profile: avro
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: deal-avro-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081

