spring:
  profiles:
    active:
      - avro

---

spring:
  config:
    activate:
      on-profile: string
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: deal-avro-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      properties:
        schema.registry.url: http://localhost:8081

---

spring:
  config:
    activate:
      on-profile: avro
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: deal-avro-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retries: 3
      properties:
        schema.registry.url: http://localhost:8081
